SELECT BOARD.TITLE, BOARD.BOARD_ID, 
REPLY.REPLY_ID, REPLY.WRITER_ID, REPLY.CONTENTS, DATE_FORMAT(REPLY.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD AS BOARD, USED_GOODS_REPLY AS REPLY
WHERE BOARD.BOARD_ID = REPLY.BOARD_ID
AND BOARD.CREATED_DATE >= '2022-10-01' AND BOARD.CREATED_DATE <= '2022-10-31'
ORDER BY REPLY.CREATED_DATE ASC, BOARD.TITLE ASC